/*
 *
 * Copyright (c) 2026 GaraKrral
 *
 * Licensed under the GPLv3 License.
 * See LICENSE file in the project root for full license information.
 *
 */

package mc.garakrral.geckos.datagen;

import java.util.Set;

import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.loot.BlockLootSubProvider;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraft.world.level.block.Block;

import mc.garakrral.geckos.block.ModBlocks;

/**
 * Generates block loot tables for the mod's blocks.
 */
public class ModBlockLootTableProvider extends BlockLootSubProvider {
    /**
     * Creates the provider.
     *
     * @param registries holder lookup provider used during loot generation
     */
    protected ModBlockLootTableProvider(HolderLookup.Provider registries) {
        super(Set.of(), FeatureFlags.REGISTRY.allFlags(), registries);
    }

    /**
     * Defines loot behavior for known mod blocks.
     */
    @Override
    protected void generate() {
        this.dropSelf(ModBlocks.GECKO_STATUE.get());
    }

    /**
     * Returns every block that should have loot generated by this provider.
     *
     * @return iterable over registered mod blocks
     */
    @Override
    protected Iterable<Block> getKnownBlocks() {
        return ModBlocks.BLOCKS.getEntries().stream().map(Holder::value)::iterator;
    }
}
